#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#runApplication cartesianMesh

killall pimpleFoam

#rm -r proc*

#rm -f log.decomposePar
rm -f log.mpirun
runApplication mpirun -np 24 pimpleFoam -parallel
#runApplication paraFoam &

rm -f log.reconstructPar
runApplication reconstructPar -latestTime
#rm -r proc*

#------------------------------------------------------------------------------
