#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

# Remove surface and features
rm -f constant/triSurface/cylinder.eMesh*
rm -r constant/extendedFeatureEdgeMesh
rm -r proc*
rm -r postProc*
rm -r constant/polyMesh
rm -f log*

rm -r 0

#---

cp -r 0.orig/ 0

rm -r postProc*
rm -r constant/polyMesh
rm -f log*

#cp system/simpleTemplate/controlDict system/controlDict

runApplication cartesianMesh
runApplication checkMesh -writeAllFields -writeSets vtk
runApplication postProcess -func writeCellCentres

rm -f 0/C
rm -f constant/C

#---

#killall simpleFoam

#cp system/simpleTemplate/controlDict system/controlDict
#cp system/simpleTemplate/fvSchemes system/fvSchemes
#cp system/simpleTemplate/fvSolution system/fvSolution

rm -f 0/Cx
rm -f 0/Cy
rm -f 0/Cz
rm -f 0/inletU
rm -r proc*
rm -r postPr*
rm -f log.decomposePar

#runApplication setFields

runApplication decomposePar

rm -f log.mpirun
runApplication mpirun -np 24 simpleFoam -parallel
#runApplication paraFoam &

#rm -f log.reconstructPar
#runApplication reconstructPar -latestTime
#rm -r proc*

#runApplication postProcess -func "flowRatePatch(name=inlet)" -latestTime
#---
