#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

rm -r postProc*
rm -r constant/polyMesh
rm -f log*

cp system/simpleTemplate/controlDict system/controlDict

runApplication cartesianMesh
runApplication postProcess -func writeCellCentres

rm -f 0/C

#------------------------------------------------------------------------------
