#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication decomposePar
#runApplication snappyHexMesh -overwrite
runApplication mpirun -np 24 snappyHexMesh -parallel
#runApplication reconstructParMesh -latestTime
#runApplication changeDictionary
#runApplication renumberMesh -latestTime

#rm -r proc*

#------------------------------------------------------------------------------
