#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#runApplication cartesianMesh

killall simpleFoam
killall pimpleFoam

rm -f log.reconstructPar
runApplication reconstructPar -latestTime
rm -f log.reconstructPar

postProcess -func "flowRatePatch(name=inlet)" -latestTime

rm -r proc*
rm -f log.decomposePar
rm -f log.postProcess
rm -f log.cartesianMesh

#------------------------------------------------------------------------------
