#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions


#---

killall simpleFoam

runApplication decomposePar

rm -f log.mpirun
runApplication mpirun -np 24 simpleFoam -parallel
#runApplication paraFoam &

#rm -f log.reconstructPar
#runApplication reconstructPar -latestTime
#rm -r proc*

#runApplication postProcess -func "flowRatePatch(name=inlet)" -latestTime
#---
